### ISSUE TITLE
Pressing the 'Escape' button while the cards are being inserted does not close the application.

### ISSUE THREAD

**Issue by auriorx** [Auriorx/pokemart-auto-redeemer#2]
The program is supposed to shut down if you press the 'Escape' key during the code card redeeming. This hasn't worked since the 1.0 version.

**Comment by auriorx** [comment]
Please upvote the issue if you want this issue to be resolved.

**Comment by AtomaFajrovulpo** [comment]
Maybe run two processes at once? One to enter codes, one to check for ESC press, or check at a certain point during the code-entering loop if ESC is held, then **holding** ESC would stop it.

**Comment by auriorx** [comment]
Can't fix. Windows Forms only have one working thread. Because that thread is busy with the simulation, it cannot intercept the ESC key. Threading won't help here either, because putting the simulation in the thread prevents the simulation from actually executing, because only the main thread can intercept keys.
