### ISSUE TITLE
2736x1824 support

### ISSUE THREAD

**Issue by auriorx** [Auriorx/pokemart-auto-redeemer#4]
As requested by @AtomaFajrovulpo support for 2736x1824 would be nice.

**Comment by thepervysage1** [comment]
Hi, 
I tried running the application under "Self-Contained"
It is only moving the mouse pointer on the game screen.
I really liked your app and love the idea of redeeming multiple codes.
If you can suggest what should I do, that would be of great help !!
Thank you in advance

**Comment by auriorx** [comment]
Won't fix
