### ISSUE TITLE
Press ctrl+s but nothing happen

### ISSUE THREAD

**Issue by BALLD100** [Auriorx/pokemart-auto-redeemer#5]

**Comment by auriorx** [comment]
Could you provide more information?

**Comment by BALLD100** [comment]
step 4 said use ctrl+s to start redeemer, but nothing happened when i press ctrl+s

**Comment by auriorx** [comment]
I've just checked version 1.3 and I get the application to work just fine. 

Did you only try to press CTRL + S inside Pokemon TCG? One thing you could try is to keep Pokemon TCG in 'windowed' mode (as full screen as possible), drag the application to the top right corner of the screen and press CTRL + S then.

Please let me know how this works out.

**Comment by BALLD100** [comment]
Yes. I only pressed CTRL + S.  I tried the windowed mode but still not working. 
It looks like the program is running but it didn't redeem after running.

**Comment by auriorx** [comment]
Does the mouse cursor move after you start the application?

I'm not sure if I can help you, but if you have discord I can try and see what happens on your PC.

You can join me here:
https://discord.gg/UGU655

**Comment by auriorx** [comment]
It's been 5 days. I assume you've either fixed the issue or moved on. If not, you can use https://discord.gg/pFeuBRZ to join the support server.
