### ISSUE TITLE
Unable to Redeem Codes

### ISSUE THREAD

**Issue by pervfectsage** [Auriorx/pokemart-auto-redeemer#6]
Hi,
I tried to do the same steps as mentioned.
But the application is only moving the mouse pointer on the game screen.
No codes are copied or redeemed.

I really liked your app and love the idea of redeeming multiple codes.
I would really appreciate if you can help me with it.
Thank you in advance

If required, I can share screen and you can help me with the error !

**Comment by auriorx** [comment]
Hi,

Besides the movement, the mouse should perform "click" actions as well. Does the cursor move on the actual buttons you're supposed to press when manually redeeming codes?

**Comment by pervfectsage** [comment]
Yes, It hovers over the buttons which we actually use for copying and claiming codes
But I don't see it pasting codes in the code section, its always blank, while the pointer keeps moving
The mouse pointer goes to Claim Now button after 10 runs, I can see that
But there is not Code being pasted anywhere in the game screen

**Comment by auriorx** [comment]
Does it also hover over the textbox to paste the codes? I've just tried it out on my own PC and it's working just fine...
![2020-09-07 19_07_31-CompatWindow](https://user-images.githubusercontent.com/58956648/92408314-6bacb080-f13d-11ea-85f7-8aee86c68842.png)

**Comment by pervfectsage** [comment]
Yes, It does hover over the test boxes to paste the codes.
But nothing gets pasted there...the mouse just then keeps moving

**Comment by auriorx** [comment]
I'm not sure if I can help you, but if you have discord I can try and see what happens on your PC. 

You can join me here:
https://discord.gg/UGU655

**Comment by pervfectsage** [comment]
Here's a screen recording of what's happening at my end
Please check and let me know

**Comment by auriorx** [comment]
I've removed the URL to make sure no one can try to read and steal your codes.

**Comment by auriorx** [comment]
As discussed, it appears to be some weird issue which I can't reproduce and unfortunately can't solve either.

~Auriorx

**Comment by Ixaruz** [comment]
I have the same issue. it moves and clicks, but doesnt actually paste codes into the box so im at a loss as well.
