### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by HebrewLantern** [Auriorx/pokemart-auto-redeemer#7]
When I attempt to run either the self contained or framework dependent versions, nothing opens. I have tried running as admin, but it does not work

**Comment by auriorx** [comment]
I'm sorry to hear about your issue, but I'm afraid there's little I can do. I've just downloaded the 1.3 version myself and got the program running without issue. I've tried this on multiple devices as well, without issues.

Do you have any other devices where you can check if the issue you're having persists?

**Comment by HebrewLantern** [comment]
it works on other devices, just not this one. Do you know of any troubleshooting i could do? Literally no errors or windows or anything show up when I open it.

**Comment by auriorx** [comment]
Tough one... Can you send the specs of the device it's not working on?

And just a quick shout beforehand; does that device have some malware/anti-virus the other devices don't have?

**Comment by HebrewLantern** [comment]
https://pastebin.com/S8sZHfT0

**Comment by auriorx** [comment]
I was unable to find a fix with that application. 

However, I did just create a 'simple' version of the redeemer [here](https://github.com/auriorx/ptcgo-auto-redeemer-simple/releases).

Could you try that one out and see if you can get that one working?

**Comment by auriorx** [comment]
Closed due to no longer providing support for this application. 

@HebrewLantern if you still have problems with the [simpler version](https://github.com/auriorx/ptcgo-auto-redeemer-simple), please create an issue there.
